# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a022cf06d75e80a4dffe59e3933caed107a9629d1f4a6a663d398feaeda85ca1e6a59d227f372b24d9e30ae5b9272653510fa563fab9a5b89a05463ececcd84

test:
  secret_key_base: 499d6b5e6fbfe2d6fa8b716fe49ab7ff4eaa8f074695793c32b02d8e16432c64468d5035050766980fd02a710d9e1978d4c051b7af36b7297464576d97e8ced8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
